### ISSUE TITLE
Can't resolve 'react-whatsapp-widget/dist/index.css'

### ISSUE THREAD

**Issue by SaadBazaz** [proficientdesigners/react-whatsapp-chat-widget#1]
Hey there,
Thanks for the awesome repository.

I am using **Nextjs**.
I'm getting this error in _app.js:

```
error - ./pages/_app.js:3:0
Module not found: Can't resolve 'react-whatsapp-widget/dist/index.css'
  1 | import '../styles/globals.css'
  2 | import 'bootstrap/dist/css/bootstrap.css'
> 3 | import 'react-whatsapp-widget/dist/index.css'
  4 | import 'react-multi-carousel/lib/styles.css';
  5 | 
  6 | 

Import trace for requested module:

https://nextjs.org/docs/messages/module-not-found
```

Any clue on what I should do?

**Comment by proficientdesigners** [comment]
Are you importing the css in correct way, like mentioned here ?

https://github.com/proficientdesigners/react-whatsapp-chat-widget

**Comment by SaadBazaz** [comment]
I had imported the CSS underneath the WhatsApp Widget import (I copied the code from your example)

Could this be because I'm using nextjs?

**Comment by proficientdesigners** [comment]
If you could reproduce this issue in codesandbox, then we can see what’s really happening..

**Comment by SaadBazaz** [comment]
I'll see if I can get to that.
In the meanwhile I created my own widget ;) https://github.com/SaadBazaz/next-whatsapp-chat-widget

**Comment by proficientdesigners** [comment]
Now you have your own widget, so i'll mark this issue as solved.
