### ISSUE TITLE
Click issue

### ISSUE THREAD

**Issue by sercan-works** [proficientdesigners/react-whatsapp-chat-widget#5]
When click any link that area of under of whataspp app, don't click any link

**Comment by proficientdesigners** [comment]
what you mean exactly, can you elaborate it.

**Comment by sercan-works** [comment]
When we press the Whatsapp icon, a field opens. When we click on the whatsapp icon again, the opened window closes. OK. But after the window is closed, if there is a link in the area under the opened window area, the click is not performed. Could I explain?

**Comment by proficientdesigners** [comment]
Well explained!, will look in to it for the solution.. Thanks for pointing this out

**Comment by sercan-works** [comment]
You're welcome. Good work!

**Comment by orisa** [comment]
@proficientdesigners I am having this same issue. Has there been any progress yet?

**Comment by proficientdesigners** [comment]
Haven't you update the plugin yet ?

**Comment by orisa** [comment]
@proficientdesigners Just tried it. Works fine. Thanks.

**Comment by proficientdesigners** [comment]
Happy that it worked for you.
