### ISSUE TITLE
Unable to click any button under the area that covers whatsapp widget header

### ISSUE THREAD

**Issue by hasith58** [proficientdesigners/react-whatsapp-chat-widget#6]
Though the whatsapp  chat is collapsed, no any button can be clicked in  the horizontal area that covers in the "whatsapp widget header" class.
![image](https://user-images.githubusercontent.com/89238740/202145839-1a989596-d991-493c-a5a8-1eba8af0586c.png)
The not responsing  area is highlighted here.

**Comment by proficientdesigners** [comment]
Can you check if the same happens in our website --> https://proficientdesigners.com/
